/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ReadDocIdRouteImport } from './routes/read.$docId'
import { Route as SessionDocIdRouteImport } from './routes/session.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadDocIdRoute = ReadDocIdRouteImport.update({
  id: '/read/$docId',
  path: '/read/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDocIdRoute = SessionDocIdRouteImport.update({
  id: '/session/$docId',
  path: '/session/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/read/$docId': typeof ReadDocIdRoute
  '/session/$docId': typeof SessionDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/read/$docId': typeof ReadDocIdRoute
  '/session/$docId': typeof SessionDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/read/$docId': typeof ReadDocIdRoute
  '/session/$docId': typeof SessionDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/read/$docId' | '/session/$docId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/read/$docId' | '/session/$docId'
  id: '__root__' | '/' | '/library' | '/read/$docId' | '/session/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ReadDocIdRoute: typeof ReadDocIdRoute
  SessionDocIdRoute: typeof SessionDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$docId': {
      id: '/read/$docId'
      path: '/read/$docId'
      fullPath: '/read/$docId'
      preLoaderRoute: typeof ReadDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$docId': {
      id: '/session/$docId'
      path: '/session/$docId'
      fullPath: '/session/$docId'
      preLoaderRoute: typeof SessionDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ReadDocIdRoute: ReadDocIdRoute,
  SessionDocIdRoute: SessionDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
